------------------------------ 1NF----------------------------------------

CREATE TABLE VETS (
  PETID NUMBER (5),
  PETNAME VARCHAR2(50),
  PETTYPE VARCHAR2(50),
  PETAGE NUMBER (5),
  OWNER VARCHAR2(50),
  VISITDATE VARCHAR2(20),
  PROCEDURES VARCHAR2(50)
  );

--------------------------------  2NF  -----------------------------------


-- 2NF TABLE: PETS
CREATE TABLE PETS (
  PETID NUMBER PRIMARY KEY,
  PETNAME VARCHAR2(50),
  PETTYPE VARCHAR2(50),
  PETAGE NUMBER(5)
);

-- 2NF TABLE: VISITS
CREATE TABLE VISITS (
  PETID NUMBER,
  VISITDATE DATE PRIMARY KEY,
  
  CONSTRAINT FKEY_VISITS_PETS FOREIGN KEY (PETID) REFERENCES PETS (PETID)

);

-- 2NF TABLE: PROCEDURES
CREATE TABLE PROCEDURES (
  VISITDATE DATE,
  PROCEDURE_NAME VARCHAR2(50),
  CONSTRAINT FKEY_PROCEDURES_VISITS FOREIGN KEY (VISITDATE) REFERENCES VISITS (VISITDATE)

);


-- 2NF TABLE: OWNERS
CREATE TABLE OWNERS (
  PETID NUMBER (5),
  OWNER_NAME VARCHAR2(50),
  CONSTRAINT FKEY_OWNERS_PETS FOREIGN KEY (PETID) REFERENCES PETS (PETID)

);

--------------------------------  3NF  -----------------------------------
-- 3NF TABLE: OWNER
CREATE TABLE OWNER (
  OWNER VARCHAR2(50) PRIMARY KEY
);




-- 3NF TABLE: PETOWNERS
CREATE TABLE PETSOWNERS (
  PETID NUMBER (5),
  OWNER VARCHAR2(50),
  CONSTRAINT FK_PETSOWNERS_PETS FOREIGN KEY (PETID) REFERENCES PETS (PETID),
  CONSTRAINT FK_PETSOWNERS_OWNERS FOREIGN KEY (OWNER) REFERENCES OWNER (OWNER)
);

